name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on each push on the master branch
  push: {branches: ["master", "main"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: SainthixOli
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          config_theme: night
          config_order: base.header, isocalendar, languages, achievements
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # Plugin: IsoCalendar (Isometric 3D Calendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Plugin: Languages (Most used languages)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          
          # Output file name
          filename: github-metrics.svg
          
          # Committer user
          committer_token: ${{ secrets.GITHUB_TOKEN }}
